# Generated by Django 5.1.6 on 2025-02-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
